### ISSUE TITLE
Bug: Only Warlock glyps available

### ISSUE THREAD

**Issue by elpantzo** [NathanHandley/mod-ah-bot#1]
### Current Behaviour

There are only Warlock glyphs

### Expected Behaviour

Glyphs for all classes

### Steps to reproduce the problem

Step 1
Clear ah table
Step 2 fill Table

### AC rev. hash/commit

AzerothCore rev. 4cd23792db1e 2024-11-18

### Operating system

Debian

**Comment by NathanHandley** [comment]
I'm unable to reproduce this.  Attached is a picture from a local build that is using the stock config just now (after clearing the DB): 
![image](https://github.com/user-attachments/assets/2b9834c9-6e19-452a-a240-4ab2387c3743)

Ensure that you're not checking the box "usable items" in the auction browser when you search for glyphs (while on a Warlock).  Also, if you're still having the issue then double check your IDs.  There are two exclusion lists in the config.  AuctionHouseBot.DisabledItemIDs has IDs for items that are junk in general, and AuctionHouseBot.DisabledCraftedItemIDs is a list of IDs of player crafted items EXCEPT for glyphs.  If you have any non-standard item IDs, spot check the list for any glyphs you think should be showing up.  Also know that it takes a few hours on a stock config to fully populate the item list, as only 75 items gets added every 'tick' until it hits 20,000 items.

**Comment by NathanHandley** [comment]
Closed because I cannot reproduce.  But let me know if you have issues after seeing above and I'll look into it!
